# Generated by Django 4.0.6 on 2024-07-04 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bond_service_api', '0002_alter_bond_emission_isin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='bond_service_api.portfolio'),
        ),
    ]
