# Generated by Django 4.0.6 on 2024-07-04 18:57

import bond_service_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond_service_api', '0003_alter_bond_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='emission_isin',
            field=models.CharField(max_length=50, unique=True, validators=[bond_service_api.validators.validate_isin]),
        ),
        migrations.AlterField(
            model_name='bond',
            name='emission_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
